### PR TITLE
feat: typescript rewrite

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Not sure if this is worth opening or if I should just maintain a fork.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
This should close all open PRs.

- Updated all devDeps
- Switched to vitest for testing
- Added typescript types
- Added CI/CD with github actions

**Comment by OmgImAlexis** [comment]
@userpixel any thoughts on this or should I close it?

**Comment by userpixel** [comment]
Good job. Haven't had time to go through details yet but it looks good.
I'll try to find some time before end of the month and merge and deploy it.

**Comment by alexewerlof** [comment]
@OmgImAlexis for such a tiny code base TypeScript is an overkill (I've written more about this [here](https://medium.com/free-code-camp/when-should-i-use-typescript-311cb5fe801b)).

So #15 is an effort to add typescript while keeping the js code intact. Could you please give it a spin and see if I've missed something?

**Pull request closed without merging**
